### PR TITLE
Split into namespaces

### PR DESCRIPTION
**Pull request by abhi18av**
Hi team,

I have split the main code into 2 namespaces. The `core.clj` now simply contains the code relevant for loggin and the `main` method.

### CODE REVIEW

**Comment by bjpop** [comment]
Thanks @abhi18av 

This looks useful, however, a lot of lines of code are changed at once.

Can you provide  more information about the purpose of these changes, and see if there is a way we can make them without such large diffs?

**Comment by abhi18av** [comment]
Hi @bjpop 

The purpose of these changes is that generally in clojure namespaces are used extensively to make each individual namespace small. The single `core.clj` file in the project was quite big and therefore I thought that perhaps it might make sense to separate the codebase into namepaces

The core strategy was to keep the `core.clj` only related to logging and parsing the main CLI params and to move rest of the code into further namespaces. I understand that this change could be improved further and I'd be happy to accomodate any change requests.


Also, worth noting that the single namespace also works great with the new emerging `clj scripts` paradigm as mentioned here https://gist.github.com/ericnormand/6bb4562c4bc578ef223182e3bb1e72c5 which is well suited for single namespaces only.

**Comment by multimeric** [comment]
@bjpop if you:
```bash
git remote add abhi18av git@github.com:abhi18av/bionitio-clojure.git
git fetch abhi18av
```
Then you can do a git diff which shows the "moved" code distinctly from the changed code. This may make it easier to review:
```bash
git diff --color-moved=blocks remotes/origin/master remotes/abhi18av/abhinav/split-into-namespaces
```

**Comment by abhi18av** [comment]
Hi @bjpop , please let me know if there's anything pending on my side.

**Comment by bjpop** [comment]
Thanks for your contribution @abhi18av

**Pull request merged**
